config_version: 1

database:
  file: "hideandseek.db"

lobby:
  duration: 15 # This is how much time (in secods) the players gonna spend in lobby waiting for game start

match:
  hideTime: 30 # sets the default time for hiders to hide (in seconds)
  seekTime: 60 # sets the default time for seekers to find hiders (in seconds)
  maxSeeker: 3 # sets how many seekers can be choosen max for a single game (player count in the lobby might affect it)

teams:
  hiders:
    viewRange: 64.0 # sets how far the displayed cover should be seen
    solidifyCooldown: 5.0 # sets how much time a hider needs before they can solidify again (in seconds)
    timeToSolid: 3.0 # sets how much time it takes to become solid (in seconds)
    health: 3 # sets the hider's cover health
  seekers: {}
